utensils/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *
from django.contrib.auth import views as auth_views
from core.utils import *


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),
    path('dashboard/', dashboard, name='dashboard'),
    path('pos/', pos_view, name='pos_view'),
    path('sales/', sales, name='sales-view'),
    path('purchases/', purchases, name='purchases-view'),
    path('inventory/', inventory, name='inventory-view'),
    path('expenses/', expenses, name='expenses-view'),
    path('customers/', customer_view, name='customer-view'),
    path('edit_product/<str:id>/', edit_product, name='edit-product-view'),
    path('update_sale/<str:id>/', edit_sale, name='edit-sale-view'),
    path('undo_sale/<str:id>/', undo_sale, name='undo-sale-view'),



    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "recoverpw-1.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "recoverpw_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "recoverpw_set.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "recoverpw_complete.html"), name='password_reset_complete'),


    
    path('api/dash_line_data/', DashboardLineData.as_view(), name='dashboard-bar-data'),
    path('api/dash_bar_data/', DashboardBarData.as_view(), name='dashboard-bar-data'),
    path('api/monthly_sales_data/', MonthlySalesLineData.as_view(), name='monthly-sales-data'),
    path('api/monthly_purchases_data/', MonthlyPurchasesLineData.as_view(), name='monthly-purchases-data'),
    path('api/monthly_expenses_data/', MonthlyExpensesLineData.as_view(), name='monthly-expenses-data'),
    path('api/daily_analysis_data/', DailyAnalysisData.as_view(), name='daily-analysis-data'),



    path('api/pos_product_data/', AllProducts.as_view(), name='pos-product-data'),
    path('api/pos/complete_sale/', complete_sale, name='complete-sale'),

]

core/models.py
from django.db import models
from .models import *
from django.db.models import Sum

import datetime


# Create your models here.


class Product(models.Model):

    product_name = models.CharField(max_length=50, unique=True)
    quantity_in_stock = models.IntegerField(default=0)
    average_buying_price = models.IntegerField(default=0, null=True)
    selling_price = models.IntegerField(default=0)
    sale_counter =  models.IntegerField(default=0)
    purchase_counter =  models.IntegerField(default=0)

    def __str__(self):

        return '%s' % self.product_name

    def selling_stock_value(self):

        selling_stock_value = self.selling_price * self.quantity_in_stock
        return selling_stock_value

    
    def buying_stock_value(self):

        buying_stock_value = self.average_buying_price * self.quantity_in_stock
        return buying_stock_value



class Purchase(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    buying_price = models.IntegerField()
    total_cost = models.IntegerField()
    date_bought = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return '%s, %s, %s, %s' % (self.product, self.quantity, self.buying_price, self.date_bought)


class Customer(models.Model):

    name = models.CharField(max_length=50, unique=True)
    contact = models.CharField(max_length=50, null=True)


    def __str__(self):

        return '%s, %s' % (self.name, self.contact)


class Sale(models.Model):

    S_CHOICES = [
        ('PENDING', 'PENDING'),
        ('PAID', 'PAID'),
    ]


    products = models.JSONField(null=True, blank=True)
    total_cost = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    actual_cost = models.IntegerField(default=0)
    date_sold = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=S_CHOICES, default='PENDING')
    customer_name = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    paid_amount = models.IntegerField()

    def __str__(self):

        return '%s, %s, %s' % (self.id, self.actual_cost, self.status)


    def balance(self):

        unpaid_balance = self.actual_cost - self.paid_amount
        return unpaid_balance


class MonthlyTotalSales(models.Model):

    month_and_year = models.DateField(auto_now_add=True)
    total_amount = models.IntegerField(default=0)
    profit = models.IntegerField(default=0)
    sales_target = models.IntegerField(default=0)

    def __str__(self):

        return '%s, %s' % (self.month_and_year, self.total_amount)


class MonthlyTotalPurchases(models.Model):

    month_and_year = models.DateField(auto_now_add=True)
    total_amount = models.IntegerField(default=0)

    def __str__(self):

        return '%s, %s' % (self.month_and_year, self.total_amount)


class DailySale(models.Model):

    date = models.DateField(auto_now_add=True)
    total_amount = models.FloatField(default=0)
    profit = models.FloatField(default=0)

    def __str__(self):

        return '%s, %s' % (self.date, self.total_amount)


class Damage(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    damage_value = models.IntegerField()
    damage_date = models.DateTimeField(auto_now_add=True)


class MonthlyTotalDamage(models.Model):

    month_and_year = models.DateField(auto_now_add=True)
    total_amount = models.IntegerField(default=0)

    def __str__(self):

        return '%s, %s' % (self.month_and_year, self.total_amount)


class Payment(models.Model):
    
    P_CHOICES = [
        ('M-PESA', 'M_PESA'),
        ('CASH', 'CASH'),
        ('EQUITY', 'EQUITY')
    ]

    sale_id = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True, blank=True)
    payment_id = models.CharField(max_length=50, null=True, blank=True, default="none")
    payment_choice = models.CharField(max_length=10, choices=P_CHOICES, default='CASH')
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return '%s, %s, %s' % (self.date, self.payment_choice, self.amount)


class Expense(models.Model):

    date = models.DateField()
    description = models.CharField(max_length=100)
    amount = models.PositiveIntegerField()
    action_date = models.DateField(auto_now_add=True)

    def __str__(self):

        return '%s, %s, %s' % (self.description, self.amount, self.date)
    


class MonthlyTotalExpense(models.Model):

    month_and_year = models.DateField(auto_now_add=True)
    total_amount = models.IntegerField(default=0)

    def __str__(self):

        return '%s, %s' % (self.month_and_year, self.total_amount)

templates/customers.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="page-content">


    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
          <h4 class="mb-3 mb-md-0">Customers</h4>
        </div>
        <div class="d-flex align-items-center flex-wrap text-nowrap">
          <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0" data-toggle="modal" data-target="#addCustomerModal">
            <i class="btn-icon-prepend" data-feather="file-plus"></i>
            Add New Customer
          </button>
        </div>
    </div>


    <div class="row">

      <div class="col-lg-12 col-xl-12 stretch-card">
          <div class="card">
          <div class="card-body">
              <div class="d-flex justify-content-between align-items-baseline mb-2">
                  <h6 class="card-title mb-4">All Products</h6>
              </div>
              <div class="table-responsive">
              <table id="dataTableExample" class="table table-hover mb-0">
                  <thead>
                  <tr>
                      <th class="pt-0">Name</th>
                      <th class="pt-0">Contact</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for customer in customers %}
                  <tr>
                      <td>{{customer.name}}</td>
                      <td>{{customer.contact}}</td>
                  </tr>
                  {% endfor %}
                  </tbody>
              </table>
              </div>
          </div> 
          </div>
      </div>

    </div>


    <div class="modal fade" id="addCustomerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add New Customer</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
  
            <div class="modal-body">
  
              <form class="forms-sample" method="POST" action="">
                {% csrf_token %}
                
                <div class="form-group row">
                  <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Customer Name</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="name" maxlength="50" required="" id="id_name">
                  </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Contact</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" name="contact" required="" id="id_contact">
                    </div>
                </div>
  
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-primary mr-2 mt-4">Submit</button>
                  <button class="btn btn-light mt-4"  data-dismiss="modal">Cancel</button>
                  </div>
                
  
              </form>
              
            </div>
  
            
          </div>
        </div>
    </div>

</div>


{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}


<div class="page-content">

    <div class="col-lg-6 col-xl-6  stretch-card">
        <div class="card">
          <div class="card-body">

            <form class="forms-sample" method="POST" action="">
                {% csrf_token %}
                
                <div class="form-group row">
                  <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Product Name</label>
                  <div class="col-sm-9">
                    <!-- <input type="text" class="form-control" name="product_name" maxlength="50" required="" value="{{form.product_name}}" id="id_product_name"> -->
                    {{form.product_name}}
                  </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Selling Price</label>
                    <div class="col-sm-9">
                      <!-- <input type="number" class="form-control" name="selling_price" value="0" required="" value="{{form.selling_price}}" id="id_selling_price"> -->
                      {{form.selling_price}}
                    </div>
                </div>
  
                <button type="submit" class="btn btn-primary mr-2 mt-4">Save Changes</button>             
  
            </form>

          </div>
        </div>
    </div>

</div>


{% endblock %}

templates/edit_sale.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}


<div class="page-content">

    <div class="row">

        <div class=" col-md-6  stretch-card">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">Sale Details</h4>
                <form class="forms-sample">
                    
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <h5>Customer Details: <span class="ml-2">{{sale.customer_name}}</span></h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-3">
                            <h5>Products:</h5>
                        </div>
                        <div class="col-sm-9">

                            <table class="table">
                            
                                <thead class="mb-2">
                                    <tr class="mb-4" style="border-top: 1px dashed black; border-bottom: 1px dashed black; margin-bottom: 8px;">
                                        <td>Item</td>
                                        <td>@</td>
                                        <td class="text-centre" >Qty</td>
                                        <td>Amount</td>
                                    </tr>
                                </thead>

                                <tbody class="mt-2">
                                    {% for i in sale.products %}
                                    <tr>
                                        <td>{{i.name}}</td>
                                        <td class="text-centre">Ksh {{i.price|intcomma}}</td>
                                        <td>{{i.quantity}}</td>
                                        <td>{{i.total_price}}</td>
                                
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>                                

                            </table>
                        </div>

                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <h5 class="mb-1">Actual Cost: <span class="ml-2 text-primary">Ksh {{sale.total_cost|intcomma}}</span></h5>
                            <h5>Discount: <span class="ml-2 text-warning">Ksh {{sale.discount|intcomma}}</span></h5>
                            <h5 class="mt-1">Total Cost: <span class="ml-2 text-info">Ksh {{sale.actual_cost|intcomma}}</span></h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <h5 class="mb-1">Total Paid: <span class="ml-2 text-success">Ksh {{sale.paid_amount|intcomma}}</span>  </h5>
                            <h5>Balance: <span class="ml-2 text-danger">Ksh {{sale.balance|intcomma}}</span>  </h5>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-12">
                            <a href="{% url 'undo-sale-view' sale.id %}" type="button" class="btn btn-danger mr-2 mt-4 float-right">UNDO</a>
                        </div>
                    </div>
                    
                    
    
                </form>

            </div>
            </div>
        </div>

        
        <div class="col-md-6 stretch-card">
            <div class="card">
                <div class="card-body">

                    <div class="form-sample">

                        {% if sale.status == 'PENDING' %}
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <h4 class="card-title mb-4">Add New Payment</h4>
                                <form class="forms-sample" method="POST" action="">
                                    {% csrf_token %}
                                    
                                    <div class="form-group row">
                                        <label for="exampleInputMobile" class="col-sm-3 col-form-label">Payment Choice</label>
                                        <div class="col-sm-9">
                                        <!-- <input type="number" class="form-control" name="selling_price" value="0" required="" value="{{form.selling_price}}" id="id_selling_price"> -->
                                        {{form.payment_choice}}
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="exampleInputMobile" class="col-sm-3 col-form-label">Amount</label>
                                        <div class="col-sm-9">
                                        <!-- <input type="number" class="form-control" name="selling_price" value="0" required="" value="{{form.selling_price}}" id="id_selling_price"> -->
                                        <input class="form-control" type="number" name="amount" required="" id="id_amount">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="exampleInputMobile" class="col-sm-3 col-form-label">TransID</label>
                                        <div class="col-sm-9">
                                        <!-- <input type="number" class="form-control" name="selling_price" value="0" required="" value="{{form.selling_price}}" id="id_selling_price"> -->
                                        <input class="form-control" type="text" name="payment_id" maxlength="50" id="id_payment_id">
                                        </div>
                                    </div>
                    
                                    <button type="submit" class="btn btn-primary mr-2 mt-4">Update</button>             
                    
                                </form>
                            </div>
                        </div>
                        {% endif %}

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <h4 class="card-title mt-4 text-warning">Previous Payments</h4>
                                <table class="table">
                            
                                    <thead class="mb-2">
                                        <tr class="mb-4" style="border-top: 1px dashed black; border-bottom: 1px dashed black; margin-bottom: 8px;">
                                            <td>#</td>
                                            <td>TransID</td>
                                            <td>Amount</td>
                                            <td class="text-centre" >TYPE</td>
                                            <td>DATE</td>
                                        </tr>
                                    </thead>
    
                                    <tbody class="mt-2">
                                        {% for i in payments %}
                                        <tr>
                                            <td>{{i.id}}</td>
                                            <td>{{i.payment_id}}</td>
                                            <td class="text-centre">Ksh {{i.amount|intcomma}}</td>
                                            <td>{{i.payment_choice}}</td>
                                            <td>{{i.date}}</td>
                                    
                                        </tr>
                                        {% endfor %}
                                        
                                    </tbody>                                
    
                                </table>
                                
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
        

    </div>
</div>


{% endblock %}

templates/expenses.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}


<div class="page-content">


  <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
      <div>
        <h4 class="mb-3 mb-md-0">Expenses</h4>
      </div>
      <div class="d-flex align-items-center flex-wrap text-nowrap">
        <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0" data-toggle="modal" data-target="#addExpenseModal">
          <i class="btn-icon-prepend" data-feather="file-plus"></i>
          Add New Expenses
        </button>
      </div>
  </div>


  <div class="row">
    <div class="col-12 col-xl-12 stretch-card">
      <div class="row flex-grow">

        <div class="col-md-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-baseline">
                <h6 class="card-title mb-2">{{expense_month_name}} Expenses</h6>
              </div>
              <div class="row">
                <div class="col-12 col-md-12 col-xl-12">
                  <h3 class="mb-2">Ksh {{monthly_expense.total_amount|intcomma}}</h3>
                  <div class="d-flex align-items-baseline">
                    {% if monthly_percent_change < 0 %}
                    <p class="text-success">
                      <span>+{{monthly_percent_change}}%</span>
                      <i data-feather="arrow-up" class="icon-sm mb-1"></i>
                    </p>
                    {% elif monthly_percent_change > 1 %}
                    <p class="text-danger">
                      <span>{{monthly_percent_change}}%</span>
                      <i data-feather="arrow-down" class="icon-sm mb-1"></i>
                    </p>
                    {% else %}
                    <p class="text-danger">
                      <span>{{monthly_percent_change}}%</span>
                    </p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-baseline">
                <h6 class="card-title mb-2">6 Months Expenses</h6>
              </div>
              <div class="row">
                <div class="col-6 col-md-12 col-xl-12">
                  <h3 class="mb-2">Ksh {{six_months_expenses|intcomma}}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div> <!-- row -->

  <div class="row mt-4">
    <div class="col-12 col-xl-12 grid-margin stretch-card">
      <div class="card overflow-hidden">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-baseline mb-4 mb-md-3">
            <h6 class="card-title mb-0">Expenses Analysis</h6>
          </div>
          <div class="row align-items-start mb-2">
            <div class="col-md-7">
              <p class="text-muted tx-13 mb-3 mb-md-0">Graphical Analysis of Total Monthly Expenses</p>
            </div>
          </div>
          <div class="row" >
            <canvas id="monthlyExpensesChart" height="400" width="1000"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- row -->


  <div class="row">
  
    <div class="col-lg-12 col-xl-12 stretch-card">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-baseline mb-2">
            <h6 class="card-title mb-0">All Expenses</h6>
            <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0" data-toggle="modal" data-target="#addExpenseModal">
              <i class="btn-icon-prepend" data-feather="file-plus"></i>
              Add New Expenses
            </button>
          </div>
          <div class="table-responsive">
            <table id="dataTableExample" class="table">
              <thead >
                <tr >
                  <th>#</th>
                  <th>Date</th>
                  <th class="pt-0">Description</th>
                  <th class="pt-0">Amount</th>
                </tr>
              </thead>
              <tbody>
                {% for expense in all_expenses %}
                <tr>
                  <td>{{expense.id}}</td>
                  <td>{{expense.date}}</td>  
                  <td>{{expense.description}}</td>
                  <td>Ksh {{expense.amount|intcomma}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div> 
      </div>
    </div>
    
  </div> <!-- row -->



  <div class="modal fade" id="addExpenseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add New Expense</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">

            <form class="forms-sample" method="POST" action="">
              {% csrf_token %}
              
              <div class="form-group row">
                <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Date</label>
                <div class="col-sm-9">
                  <input type="date" name="date" class="form-control date datepicker" required="" id="id_date">
                </div>
              </div>
              <div class="form-group row">
                  <label for="exampleInputMobile" class="col-sm-3 col-form-label">Description</label>
                  <div class="col-sm-9">
                      <input type="text" name="description" class="form-control" placeholder="short description" maxlength="100" required="" id="id_description">
                  </div>
              </div>
              <div class="form-group row">
                  <label for="exampleInputMobile" class="col-sm-3 col-form-label">Amount</label>
                  <div class="col-sm-9">
                      <input type="number" name="amount" class="form-control" min="0" required="" id="id_amount">
                  </div>
              </div>

                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary mr-2 mt-4">Submit</button>
                <button class="btn btn-light mt-4"  data-dismiss="modal">Cancel</button>
                </div>
              

            </form>
            
          </div>

          
        </div>
      </div>
  </div>


</div>


{% endblock %}

templates/recoverpw-1.html
{% load static %}

<!DOCTYPE html>
<html lang="">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,initial-scale=1.0">
      <link rel="icon" href="<%= BASE_URL %>favicon.ico">
      <title>BIZZY</title>
      <!-- core:css -->
      <link rel="stylesheet" href="{% static 'assets/vendors/core/core.css' %}">
      <!-- endinject -->
      <!-- plugin css for this page -->
      <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}">
      <!-- end plugin css for this page -->
      <!-- inject:css -->
      <link rel="stylesheet" href="{% static 'assets/fonts/feather-font/css/iconfont.css' %}">
      <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
      <!-- endinject -->
      <!-- Layout styles -->  
      <link rel="stylesheet" href="{% static 'assets/css/demo_2/style.css' %}">
      <!-- End layout styles -->
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    </head>

    <body>
        <div class="main-wrapper">

            <div class="page-wrapper full-page">
                <div class="page-content d-flex align-items-center justify-content-center">

                    <div class="row w-100 mx-0 auth-page">
                        <div class="col-md-8 col-xl-6 mx-auto">
                            <div class="card">
                                <div class="row">
                                    <div class="col-md-4 pr-md-0">
                                        <div class="auth-left-wrapper">

                                        </div>
                                    </div>
                                    <div class="col-md-8 pl-md-0">
                                    <div class="auth-form-wrapper px-4 py-5">
                                        <h5 class="text-muted font-weight-normal mb-4">Enter your Email and instructions will be sent to you!</h5>
                                        <form class="forms-sample" method="POST" action="">
                                            {% csrf_token %}

                                            <div class="form-group">
                                                <label for="id_email">Email</label>
                                                 <input class="form-control" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email">
                                            </div>

                                            <div class="mt-3">
                                                <button type="submit" class="btn btn-primary mr-2 mb-2 mb-md-0 text-white">Reset Password</button>
                                                <a href="{% url 'login-view'%}" class="btn-icon-text mb-2 mb-md-0">
                                                    Remember it?
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </body>

</html>